CREATE DATABASE IF NOT EXISTS barista;
USE barista;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE,
  password VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reservations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100),
  date DATE,
  time TIME,
  people INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
